#!/bin/sh

TARGET=##TARGET##
TEMP=##TEMP##

mkdir -p $TEMP
git --work-tree=$TEMP checkout -f

rsync -a --progress --delete --delete-excluded\
  --exclude .git/ --exclude .gitignore\
  $TEMP $TARGET
rm -rf $TEMP
