#!/bin/ksh

if [ $(id -u) -ne 0 ]
then
  echo "Must be run as su."
  exit
fi

POST_RECEIVE_PATH=/home/httpdconfig/httpd.conf/hooks/post-receive

echo "Making sample httpd.conf at /etc/httpd/httpd.conf..."
mkdir /etc/httpd
cp /etc/examples/httpd.conf /etc/httpd/httpd.conf
echo "Done!"

echo "Adding user 'httpdconfig'..."
useradd -mv -b /home/httpdconfig -d /home/httpdconfig httpdconfig
chown -R httpdconfig /etc/httpd/ 
chown -R httpdconfig /etc/httpd/*
echo "permit httpdconfig nopass rcctl reload httpd" >> /etc/doas.conf
echo "Done!"

echo "Setting httpd to read from custom config..."
echo "Enabling httpd..."
rcctl enable httpd
rcctl set httpd flags -f /etc/httpd/httpd.conf
echo "Done!"

echo "Initializing httpd.conf repo..."
git init --bare /home/httpdconfig/httpd.conf
create_post_receive\
  "\/home\/httpdconfig\/temp\/" "\/etc\/httpd\/" >\
  $POST_RECEIVE_PATH
echo "rcctl reload httpd" >> $POST_RECEIVE_PATH
chown -R httpdconfig /home/httpdconfig/httpd.conf
echo "Done!"
